sh-movie-tracker/src/components/App/App.js
sh-movie-tracker/src/utils/fetchMovie.js

-Created makeMovies function that maps over movies and sets state with cleaned data

Fetch movies

---

package-lock.json
package.json
src/actions/index.js
src/components/App/App.js
src/index.js
src/reducers/addMoviesReducer.js
src/reducers/index.js

-Connected files with Redux
-Movies array is now in global state
Co-Authored By: Sally Haefling <sallyhaefling@gmail.com>

Initiated global state with the movie array pulled from the api

---

src/components/App/App.js
src/containers/MovieContainer/MovieContainer.js
src/reducers/addMoviesReducer.js

Displayed movie inside of MovieContainer and fix url inside of App where clean data is living. 
TODO: Move clean data to cleaners file.

Display movies

---

src/components/Movie/Movie.js
src/containers/MovieContainer/MovieContainer.js

-Mapped over movies array and displayed movie info on page
Co-authored by: Lauren Boyer <lboyer4@outlook.com>

Map over movies to display movie info correctly

---

src/containers/Login/Login.js
src/containers/Signup/Signup.js
src/utils/fetchUsers.js

-Add an error message if the email already exists on create account

Email error

---

src/containers/Login/Login.js
src/containers/Signup/Signup.js

-Add error if password and email dont match
-Add else conditional for loggedIn boolean in state - setState

Login error

---

src/containers/Login/Login.js
src/containers/Login/Login.scss
src/containers/Signup/Signup.js
src/containers/Signup/_Signup.scss

-Added styling to the Sign-in and Create account pages

Form styles

---

src/components/App/App.js
src/containers/Login/Login.js

-user is redirected to movie container on successful login
Co-authored-by: Sally Haefling <sallyhaefling@gmail.com>

redirect to home page on succesful login

---

src/components/App/App.js
src/components/Movie/Movie.js
src/containers/MovieContainer/MovieContainer.js
src/containers/Signup/Signup.js
src/utils/fetchUsers.js

-Made favorite button
-put favorited movie on the backend
Co-authored-by: Sally Haefling <sallyhaefling@gmail.com>

added  handle click for favorites and posted to the fetch call

---

package-lock.json
package.json
src/components/App/App.test.js
src/reducers/addMoviesReducer.test.js

Add two tests for addMoviesReducer:
-Initial state test
-New state test

Reducer testing

---

src/components/App/App.js
src/components/Header/_Header.scss
src/components/Movie/Movie.js
src/components/Movie/_Movie.scss
src/components/MovieDetails/MovieDetails.js

Co-authored-by: Lauren Boyer <lboyer4@outlook.com>
-Style buttons 
-Add MovieDetails component

Add moviedetails component and style

---

src/components/App/App.js
src/components/Movie/Movie.js
src/components/Movie/Movie.test.js
src/components/MovieDetails/MovieDetails.js
src/components/MovieDetails/_MovieDetails.scss
src/utils/mockData.js

-refactored Route to movieDetails to pass down movie details
-added styling so font was visible on page
-added alt tag to image to remove error

Movie details

---

src/components/Movie/Movie.js

-moved make account message
-removed title from movie page

fixed movie merge conflicts

---

src/components/MovieDetails/MovieDetails.js

Removed console.log from MovieDetails

Remove console logs

---

src/reducers/setFavoritesReducer.test.js
src/reducers/updateLoginReducer.test.js

-Test setFavorites and updateLogin reducers

Test update login

---

src/containers/MovieContainer/MovieContainer.js
src/containers/MovieContainer/MovieContainer.test.js
src/containers/MovieContainer/__snapshots__/MovieContainer.test.js.snap
src/reducers/setFavoritesReducer.test.js
src/reducers/updateLoginReducer.test.js

MovieContainer container fully tested

Test movie container

---

src/containers/FavoriteContainer/FavoriteContainer.js
src/containers/FavoriteContainer/FavoriteContainer.test.js
src/containers/FavoriteContainer/__snapshots__/FavoriteContainer.test.js.snap
src/containers/MovieContainer/MovieContainer.test.js

Test FavoriteContainer fully tested

Test favoriteContainer complete

---

src/components/Header/Header.js
src/components/Header/Header.test.js

Test Header complete

---

src/components/Header/Header.js

Take out log

---

src/components/Movie/Movie.js
src/components/Movie/Movie.test.js
src/components/Movie/__snapshots__/Movie.test.js.snap
src/containers/Login/Login.js
src/containers/Login/Login.test.js
src/containers/Login/__snapshots__/Login.test.js.snap
src/reducers/index.js

-added tests to login 
-deleted console logs

Login test

---

src/utils/fetchUsers.js
src/utils/fetchUsers.test.js

Test fetchUsers overall - one of the async tests (for ok:false response) is skipped; ran into issues trying to get it to reject and not resolve.

Test fetch users
